#' Create a blueprint figure of your multiverse pipeline
#'
#' @param .grid a pipeline \code{tibble}
#' @param splines how to draw edges connecting nodes in Graphviz, defaults to
#'   \code{splines = "line"}
#' @param graph logical, whether or not to draw the graph in the viewing pane
#' @param show_code logical, whether to print out the dot code to the console
#' @param ... additional arguments passed to \code{\link[DiagrammeR]{grViz}}
#'
#' @return if \code{graph = TRUE}, the object will be a Graphviz diagram
#'   generated by \code{\link[DiagrammeR]{grViz}}. If \code{graph = FALSE}, the output
#'   will be the literal dot code to generate the graph, which could be used to
#'   manually edit or customize the graph further.
#' @export
#'
#' @examples
#'
#' library(tidyverse)
#' library(multitool)
#'
#' ## Simulate some data
#' the_data <-
#'   data.frame(
#'     id   = 1:500,
#'     iv1  = rnorm(500),
#'     iv2  = rnorm(500),
#'     iv3  = rnorm(500),
#'     mod1 = rnorm(500),
#'     mod2 = rnorm(500),
#'     mod3 = rnorm(500),
#'     cov1 = rnorm(500),
#'     cov2 = rnorm(500),
#'     dv1  = rnorm(500),
#'     dv2  = rnorm(500),
#'     include1 = rbinom(500, size = 1, prob = .1),
#'     include2 = sample(1:3, size = 500, replace = TRUE),
#'     include3 = rnorm(500)
#'   )
#'
#' full_pipeline <-
#'   the_data |>
#'   add_filters(include1 == 0,include2 != 3,include2 != 2,scale(include3) > -2.5) |>
#'   add_variables("ivs", iv1, iv2, iv3) |>
#'   add_variables("dvs", dv1, dv2) |>
#'   add_variables("mods", starts_with("mod")) |>
#'   add_preprocess(process_name = "Standardize IVs", 'mutate({ivs} = scale({ivs}))') |>
#'   add_preprocess(process_name = "Standardize Moderators", mutate({mods} := scale({mods}))) |>
#'   add_summary_stats("IV Summary Stats", starts_with("iv"), c("mean", "sd")) |>
#'   add_summary_stats("DV Summary Stats", starts_with("dv"), c("skewness", "kurtosis")) |>
#'   add_correlations("Between Predictors", matches("iv|mod|cov"), focus_set = c(cov1,cov2)) |>
#'   add_correlations("Between Outcomes", matches("dv|mod"), focus_set = matches("dv")) |>
#'   add_cron_alpha("unp_scale", c(iv1,iv2,iv3)) |>
#'   add_cron_alpha("vio_scale", starts_with("mod")) |>
#'   add_model("no covariates",lm({dvs} ~ {ivs} * {mods})) |>
#'   add_model("covariates",lm({dvs} ~ {ivs} * {mods} + cov1)) |>
#'   add_postprocess("simple slopes", "sim_slopes(pred = condition, modx = {ivs}, modx_values = c(-1,1))") |>
#'   add_postprocess("plotting interactions", ggpredict(terms = c("{ivs} [-1,1]", "{mods} [-1,1]")))
#'
#' # Default graph produced
#' blueprint(full_pipeline)
#'
#' # Change the way edges look
#' blueprint(full_pipeline, splines = "polyline")
#'
#' # Take a look at the dot code
#' blueprint(full_pipeline, graph = FALSE, show_code = TRUE)
blueprint <- function(.grid, splines = 'line', graph = TRUE, show_code = FALSE, ...){

  pipeline <-
    .grid |>
    dplyr::mutate(
      code = stringr::str_replace_all(code, c(">=" = "bigger than or equal to",
                                              "<=" = "less than or equal to",
                                              " > "  = " bigger than ",
                                              " < "  = " less than ",
                                              "==" = "equals",
                                              "!=" = "does not equal",
                                              "%in%.*$" = 'is any value',
                                              "scale\\((.*)\\)" = "z-scored \\1 is"))
    )

  pipe_nodes <- list()
  pipe_edges <- list()
  pipe_invis <- list()

  blueprint_start <-
    glue::glue(
      .open = "<", .close = ">",.trim = FALSE,
      "digraph your_blueprint {\n",
      "    graph [\n",
      "           layout = dot\n",
      "           overlap = false\n",
      "           rankdir = TD\n",
      "           splines = <splines>\n",
      "          ]\n"
    )

  if("variables" %in% unique(.grid$type)){
    v_data <-
      pipeline |>
      dplyr::filter(type == "variables")

    v_n_sets <-
      v_data |>
      dplyr::group_by(group) |>
      dplyr::count() |>
      nrow()

    v_group_nodes <-
      v_data |>
      dplyr::group_by(group) |>
      dplyr::summarize(vars = paste0(code, collapse = ", ")) |>
      glue::glue_data(.trim = FALSE, "<B>{group}</B><BR ALIGN = 'LEFT'/> {vars} <BR ALIGN = 'LEFT'/>")

    v_nodes <-
      glue::glue(
        .trim = FALSE,
        "variables [label = <<B>variables</B> <BR/> {v_n_sets} sets>]\n    ",
        "variables_details [label = <{v_group_nodes |> paste(collapse = ' <BR ALIGN = \"LEFT\"/>')}>]\n",
      )

    v_edges <-
      glue::glue(
        "variables_details -> variables [tailport = 'e' headport = 'w' arrowhead = none]\n"
      )

    pipe_nodes$v_nodes <- v_nodes
    pipe_edges$v_edges <- v_edges
    pipe_invis$v_invis <- "variables_details -> variables"
  }

  if("filters" %in% unique(.grid$type)){
    f_data <-
      pipeline |>
      dplyr::filter(type == "filters")

    f_n_sets <-
      f_data |>
      dplyr::group_by(group) |>
      dplyr::count() |>
      nrow()

    f_group_nodes <-
      f_data |>
      dplyr::group_by(group) |>
      dplyr::summarize(filters = paste0(code, collapse = " <BR ALIGN = 'LEFT'/> ")) |>
      glue::glue_data(.trim = FALSE, "<B>{group}</B><BR ALIGN = 'LEFT'/> {filters} <BR ALIGN = 'LEFT'/>")

    f_nodes <-
      glue::glue(
        .trim = FALSE,
        "    filters [label = <<B>filters</B> <BR/> {f_n_sets} sets>]\n    ",
        "filters_details [label = <{f_group_nodes |> paste(collapse = ' <BR ALIGN = \"LEFT\"/>')}>]\n",
      )

    f_edges <-
      glue::glue(
        .trim = FALSE,
        "    filters_details -> filters [tailport = 'w' headport = 'e' arrowhead = none]\n"
      )

    pipe_nodes$f_nodes <- f_nodes
    pipe_edges$f_edges <- f_edges
    pipe_invis$f_invis <- "    filters -> filters_details"
  }

  if("preprocess" %in% unique(.grid$type)){
    pre_data <-
      pipeline |>
      dplyr::filter(type == "preprocess")

    pre_n_sets <-
      pre_data |>
      dplyr::group_by(group) |>
      dplyr::count() |>
      nrow()

    pre_group_nodes <-
      pre_data |>
      glue::glue_data(.trim = FALSE, " - {group} <BR ALIGN = 'LEFT'/>")

    pre_nodes <-
      glue::glue(
        .trim = FALSE,
        "    preprocess [label = <<B>Preprocessing Steps</B> <BR/> <BR ALIGN = 'LEFT'/> {pre_group_nodes |> paste(collapse = '')}>]\n"
      )

    pre_edges <-
      glue::glue(
        .trim = FALSE,
        "{ifelse(!is.null(pipe_nodes$f_nodes), '    filters -> preprocess [headport = \\'n\\' tailport = \\'s\\']\n', '')}",
        "{ifelse(!is.null(pipe_nodes$v_nodes), '    variables -> preprocess [headport = \\'n\\' tailport = \\'s\\']\n', '')}"
      )

    pipe_nodes$pre_nodes <- pre_nodes
    pipe_edges$pre_edges <- pre_edges
  }

  pipe_nodes$n_node <-
    pipeline |>
    dplyr::filter(type %in% c("filters","variables")) |>
    dplyr::group_by(group) |>
    dplyr::count() |>
    dplyr::pull(n) |>
    purrr::accumulate(`*`) |>
    max() |>
    paste0("    n_data [label = '", ... =  _, " datasets']\n")

  if(!is.null(pipe_nodes$pre_nodes)){
    n_edges <-
      glue::glue(
        "{ifelse(!is.null(pipe_nodes$pre_nodes), '    preprocess -> n_data [headport = \\'n\\' tailport = \\'s\\']\n', '')}"
      )
  } else{
    n_edges <-
      glue::glue(
        "{ifelse(!is.null(pipe_nodes$f_nodes), 'filters -> n_data [headport = \\'n\\' tailport = \\'s\\']\n', '')}",
        "{ifelse(!is.null(pipe_nodes$v_nodes), 'variables -> n_data [headport = \\'n\\' tailport = \\'s\\']\n', '')}"
      )
  }

  pipe_edges$n_edges <- n_edges

  if("models" %in% unique(.grid$type)){
    m_data <-
      pipeline |>
      dplyr::filter(type == "models")

    m_n_sets <-
      m_data |>
      dplyr::group_by(code) |>
      dplyr::count() |>
      nrow()

    m_group_nodes <-
      m_data |>
      dplyr::mutate(model_num = 1:dplyr::n()) |>
      glue::glue_data(.trim = FALSE, "    model_{model_num} [label = <<B>{group} model</B> <BR/> {code} <BR/>>]\n")

    m_edges <- glue::glue(.trim = FALSE, "    n_data -> model_{1:m_n_sets}\n")

    ms_node <-
      pipeline |>
      dplyr::filter(type %in% c("filters","variables", "models")) |>
      dplyr::mutate(group = ifelse(type=="models", "model", group)) |>
      dplyr::group_by(group) |>
      dplyr::count() |>
      dplyr::pull(n) |>
      purrr::accumulate(`*`) |>
      max() |>
      paste0("    models [label = '", ... =  _, " models']\n")

    ms_edge <- glue::glue(.trim = FALSE, "    model_{1:m_n_sets} -> models\n")

    pipe_nodes$m_nodes <- m_group_nodes
    pipe_edges$m_edges <- m_edges
    pipe_nodes$ms_node <- ms_node
    pipe_edges$ms_node <- ms_edge
  }

  if("postprocess" %in% unique(.grid$type)){
    post_data <-
      pipeline |>
      dplyr::filter(type == "postprocess")

    post_n_sets <-
      post_data |>
      dplyr::group_by(group) |>
      dplyr::count() |>
      nrow()

    post_group_nodes <-
      post_data |>
      glue::glue_data(.trim = FALSE, "- {group} <BR ALIGN = 'LEFT'/>")

    post_nodes <-
      glue::glue(
        .trim = FALSE,
        "    postprocess [label = <<B>Post-processing steps</B> <BR/><BR ALIGN = 'LEFT'/> {post_group_nodes |> paste(collapse = '')}>]\n"
      )

    post_edges <- "    models -> postprocess\n"

    pipe_nodes$post_nodes <- post_nodes
    pipe_edges$post_edges <- post_edges
  }

  if("corrs" %in% unique(.grid$type) || "cron_alpha" %in% unique(.grid$type) || "summary_stats" %in% unique(.grid$type)){

    summary_pipe <- list()

    if("corrs" %in% unique(.grid$type)){
      c_data <-
        pipeline |>
        dplyr::filter(type == "corrs", stringr::str_detect(group, "rs$")) |>
        dplyr::mutate(group = stringr::str_remove(group, "_rs$"))

      c_n_sets <-
        c_data |>
        dplyr::group_by(group) |>
        dplyr::count() |>
        nrow()

      c_group_nodes <-
        c_data |>
        dplyr::mutate(code_pipe = glue::glue("{attr(.grid, 'base_df')} |> {stringr::str_extract(code, '^.*\\\\|\\\\>')} ncol()")) |>
        dplyr::mutate(code_result = purrr::map_chr(code_pipe, function(x) rlang::eval_tidy(rlang::parse_expr(x)) |> paste(collapse = ", "))) |>
        glue::glue_data("<BR ALIGN='LEFT'/>- {group}, {code_result} variables")

      summary_pipe$corrs <- glue::glue("<B>Correlations</B>{c_group_nodes |> paste(collapse = '')}<BR ALIGN='LEFT'/>")
    }

    if("cron_alphas" %in% unique(.grid$type)){
      a_data <-
        pipeline |>
        dplyr::filter(type == "cron_alphas")

      a_n_sets <-
        a_data |>
        dplyr::group_by(group) |>
        dplyr::count() |>
        nrow()

      a_group_nodes <-
        a_data |>
        dplyr::mutate(code_pipe = glue::glue("{attr(.grid, 'base_df')} |> {str_extract(code, '^.*\\\\|\\\\>')} ncol()")) |>
        dplyr::mutate(code_result = purrr::map_chr(code_pipe, function(x) rlang::eval_tidy(rlang::parse_expr(x)) |> paste(collapse = ", "))) |>
        glue::glue_data("<BR ALIGN='LEFT'/> - {group}, {code_result} items")

      summary_pipe$alphas <- glue::glue("<B>Internal Consistencies</B>{a_group_nodes |> paste(collapse = '')}<BR ALIGN='LEFT'/>")
    }

    if("summary_stats" %in% unique(.grid$type)){
      s_data <-
        pipeline |>
        dplyr::filter(type == "summary_stats")

      s_n_sets <-
        s_data |>
        dplyr::group_by(group) |>
        dplyr::count() |>
        nrow()

      s_group_nodes <-
        s_data |>
        dplyr::mutate(code_pipe = glue::glue("{attr(.grid, 'base_df')} |> {code} |> names() |> str_remove('^.*_') |> unique()")) |>
        dplyr::mutate(code_result = purrr::map_chr(code_pipe, function(x) rlang::eval_tidy(rlang::parse_expr(x)) |> paste(collapse = "<BR ALIGN='LEFT'/>   - "))) |>
        glue::glue_data("- {group} <BR ALIGN = 'LEFT'/>   - {code_result} <BR ALIGN='LEFT'/>")

      summary_pipe$summary_stats <- glue::glue("<B>Descriptive Statistics</B> <BR ALIGN='LEFT'/> {s_group_nodes |> paste(collapse = ' <BR ALIGN=\"LEFT\"/>')}")
    }

    summary_nodes <-
      glue::glue(
        .trim = FALSE,
        "    summaries [label = <{summary_pipe |> unlist() |> paste0( collapse = '<BR ALIGN=\"LEFT\"/>')}>]\n"
      )

    summary_edges <- "    n_data -> summaries"

    pipe_nodes$summaries <- summary_nodes
    pipe_edges$summaries <- summary_edges
  }


  base_type <-
    pipeline |>
    dplyr::distinct(type) |>
    dplyr::filter(type %in% c("variables", "filters")) |>
    glue::glue_data(.trim = FALSE, "base_data -> {type}")

  invis_link <- ifelse(!is.null(pipe_invis$f_invis) && !is.null(pipe_invis$v_invis),"->", "")

  invis_graph <-
    glue::glue(
      .open = "<", .close = ">", .trim = FALSE,
      "# Force varialbes and filters to appear on the same level\n",
      "    {\n",
      "     rank = same; edge[style=invis]\n",
      "     <ifelse(!is.null(pipe_invis$v_invis), pipe_invis$v_invis, '')> <invis_link> <ifelse(!is.null(pipe_invis$f_invis), pipe_invis$f_invis, '')>\n",
      "     rankdir = LR\n",
      "    }\n"
    )

  my_graph <-
    glue::glue(
      .trim = FALSE,
      "{blueprint_start}\n",
      "    # Nodes ---- \n",
      "    node [shape = rect style = 'rounded'] # Node settings\n",
      "    base_data [label = <<B>Base dataset</B> <BR/> {attr(.grid, 'base_df')}>]\n",
      "    {pipe_nodes |> unlist() |>  paste0(collapse = '')}\n",
      "    # Edges ---- \n",
      "    {base_type |> paste0(collapse = '\n    ')}\n",
      "    {pipe_edges |> unlist() |> paste0( collapse = '')}\n\n",
      "    {invis_graph}\n",
      "}"
    )

  if(show_code){
    cat(my_graph)
  }

  if(graph){
    DiagrammeR::grViz(my_graph, ...)
  } else{
    my_graph
  }
}
